name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ps:
    runs-on: ubuntu-latest
    steps:
    - run: ps -p $$ -o args= | xargs -n 1 | tail -n 1
    
  test-apt-virtualbox:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Boot OpenBSD
      uses: mario-campos/emulate@main
      with:
        operating-system: openbsd-7.6

    - run: uname -a

    - run: env

    - run: top -b

    - run: echo hello world from openbsd
