name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ openbsd-6.9, netbsd-9.2 ]
    steps:
    - run: |
        brew install vagrant qemu libvirt
        brew services start libvirt
        vagrant plugin install vagrant-libvirt
        echo --- libvirtd --help ---
        libvirtd --help
        echo --- cat /usr/local/etc/libvirt/libvirtd.conf ---
        cat /usr/local/etc/libvirt/libvirtd.conf
        echo --- ls -alR ... ---
        sudo ls -alR '/usr/local/var/run/libvirt' '/var/run/libvirt'
        echo --- find / -type s ---
        sudo find / -type s
        exit 1
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: |
        git clone https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        make hello
    - run: qemu-test/hello
