name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-apt-virtualbox:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo dmidecode --string system-product-name
        exit 1
    # - name: Cache VirtualBox
    #   id: cache-virtualbox
    #   uses: actions/cache@v4
    #   with:
    #     path: /usr
    #     key: ${{ runner.os }}-virtualbox
        
    # - name: Install VirtualBox
    #   if: steps.cache-virtualbox.outputs.cache-hit != 'true'
    #   run: sudo apt update && sudo apt install -y virtualbox
      
    # - run: VBoxManage --version
    # - run: sudo dpkg -L virtualbox
