name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ openbsd-6.9, freebsd-13.0, netbsd-9.2, hardenedbsd-13, dragonflybsd-5.2.0 ]
    steps:
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test && make hello
