name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: macos-10.15
    steps:
    - name: Try ttyd on macOS
      run: |
        curl https://bot.whatismyipaddress.com/; echo
        brew install ttyd
        sudo ttyd bash
