name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: mount
    - run: sudo df -h
    - run: dpkg -l
    - run: top -bn 1 -o +%mem
    - uses: mario-campos/qemulate@main
      with:
        operating-system: openbsd-current
