name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Bandwidth of Vagrant Cloud
      run: curl -L https://app.vagrantup.com/scotch/boxes/box/versions/3.5/providers/virtualbox.box >/dev/null
    - name: Test Bandwidth of GitHub
      run: curl -L https://github.com/mario-campos/qemu-test/releases/download/untagged-64f1cc25945c6701cb61/fbd109cd-1c36-424c-b463-3abc7726b342 >/dev/null
