name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        echo "$@"
        echo "==="
        for var in "$@"
        do
          echo "$var"
        done
    - shell: python
      run: |
        import os, sys
        os.system("cat '%s'" % sys.argv[0])
    - uses: mario-campos/qemulate@main
      with:
        operating-system: openbsd-current
