name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-netbsd:
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@less-env
      with:
        operating-system: netbsd-latest
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out

  test-freebsd:
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@less-env
      with:
        operating-system: freebsd-latest
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out

  test-openbsd:
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@less-env
      with:
        operating-system: openbsd-latest
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out
