name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat >shell <<EOF
        #!/usr/bin/perl

        use Data::Dumper;
        use strict;
        use warnings;
        unshift @ARGV, $0;
        print Dumper \@ARGV;
        EOF
        
        chmod +x shell
        sudo cp -f shell /usr/bin/bash
        sudo cp -f shell /bin/bash
    - run: uname -a
#     - uses: mario-campos/emulate@main
#       with:
#         operating-system: openbsd-6.9
#     - run: uname -a
