name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test-macos-latest:
    runs-on: macos-11
    steps:
    - run: brew list
    - run: brew install vagrant virtualbox
  
  test-macos-12:
    runs-on: macos-12
    steps:
    - run: brew list
    - run: brew install vagrant virtualbox

  test-netbsd:
    if: false
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@main
      with:
        operating-system: netbsd-latest
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out

  test-freebsd:
    if: false
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@main
      with:
        operating-system: freebsd-latest
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out

  test-openbsd:
    if: false
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@main
      with:
        operating-system: openbsd-latest
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out
