name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: |
        brew install vagrant qemu libvirt
        brew services start libvirt
        vagrant plugin install vagrant-libvirt
        echo --- libvirtd --help ---
        libvirtd --help
        echo --- ls -alR ... ---
        sudo ls -al "$XDG_RUNTIME_DIR/libvirt/libvirt-sock"
        exit 1
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: |
        git clone https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        make hello
    - run: qemu-test/hello
