name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ps:
    if: false
    runs-on: ubuntu-latest
    steps:
    - run: |
        HIJACKER="$(mktemp)"
        
        cat >"$HIJACKER" <<EOF
        FOO=BAR exec cat < "\$0"
        EOF
        
        echo "BASH_ENV=$HIJACKER" >> "$GITHUB_ENV"

    - run: echo normal command
    
  test-apt-virtualbox:
    runs-on: ubuntu-latest
    steps:
    - name: Boot OpenBSD
      uses: mario-campos/emulate@main
      with:
        operating-system: openbsd-7.6

    - run: uname
    - run: hostname
    - run: top -b
    - run: ping -c 4 google.com
