name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-large-file-bandwidth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Bandwidth of Vagrant Cloud (1.2 GB)
      run: |
        curl -L https://app.vagrantup.com/scotch/boxes/box/versions/3.5/providers/virtualbox.box >/dev/null
    - name: Test Bandwidth of GitHub (1.2 GB)
      run: |
        curl -L https://github.com/mario-campos/qemu-test/releases/download/bandwidth-test/large.box >/dev/null
  test-medium-file-bandwidth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Bandwidth of Vagrant Cloud (466 MB)
      run: |
        curl -L https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/202110.26.0/providers/hyperv.box >/dev/null
    - name: Test Bandwidth of GitHub (466 MB)
      run: |
        curl -L https://github.com/mario-campos/qemu-test/releases/download/bandwidth-test/medium.box >/dev/null
  test-small-file-bandwidth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Bandwidth of Vagrant Cloud (250 MB)
      run: |
        curl -L https://app.vagrantup.com/debian/boxes/jessie64/versions/8.11.0/providers/libvirt.box >/dev/null
    - name: Test Bandwidth of GitHub (250 MB)
      run: |
        curl -L https://github.com/mario-campos/qemu-test/releases/download/bandwidth-test/small.box >/dev/null
