name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: macos-10.15
    steps:
    - name: Try ttyd on macOS
      run: |
        brew install ttyd
        echo "Connect to ttyd at http://admin:qemu-test@$(curl https://bot.whatismyipaddress.com):7681/."
        sudo ttyd --credential admin:qemu-test bash
