name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate-openbsd:
    runs-on: macos-10.15
    steps:
    - name: boot freebsd-13.0
      uses: mario-campos/emulate@main
      with:
        operating-system: freebsd-13.0
    - name: hello world
      run: echo hello world
    - name: uname
      run: uname -a
    - name: df
      run: df -h
