name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ openbsd-6.9 ]
    steps:
    - run: |
        curl https://bot.whatismyipaddress.com
        ip addr
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: uname -a && ifconfig
