name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate:
    runs-on: macos-10.15
    steps:
    - name: pkg-config openssl
      run: pkg-config --silence-errors --cflags --libs openssl libbsd
      env:
        PKG_CONFIG_PATH: /usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/pkgconfig
    - name: pkg-config libbsd
      run: pkg-config --silence-errors --libs libbsd
