name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo $@
      shell: bash
    - run: |
        import sys
        print(sys.argv)
      shell: python
    - uses: mario-campos/qemulate@main
      with:
        operating-system: openbsd-current
