name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: general commands
      run: |
        brew install qemu libvirt dbus
        brew services start dbus
        brew services start libvirt
        brew services list
        exit 1
        echo --- vagrant plugin ... ---
        vagrant plugin install vagrant-libvirt
        echo --- libvirtd --help ---
        libvirtd --help
        echo --- cat /usr/local/etc/libvirt/libvirtd.conf ---
        cat /usr/local/etc/libvirt/libvirtd.conf
        exit 1
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: |
        git clone https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        make hello
    - run: qemu-test/hello
