name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-apt-virtualbox:
    runs-on: ubuntu-latest
    steps:
    - name: Install VirtualBox
      run: sudo apt update && sudo apt install -y virtualbox
    - run: VBoxManage --version
    - name: Download Vagrant
      run: wget -O $RUNNER_TEMP/vagrant.zip https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3_linux_amd64.zip
    - run: unzip vagrant.zip
      working-directory: ${{ runner.temp }}
    - run: $RUNNER_TEMP/vagrant --version
          
