name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-apt-virtualbox:
    runs-on: ubuntu-latest
    steps:
    - name: Boot OpenBSD
      uses: mario-campos/emulate@main
      with:
        operating-system: openbsd-7.6

    - run: uname -a

    - run: env

    - run: top -b
