name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install libbsd libbsd-dev
    - run: ls -lR /usr/include
