name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate:
    strategy:
      matrix:
        os: [ openbsd-latest, freebsd-latest ]
    runs-on: macos-10.15
    steps:
    - name: search for openssl.pc
      run: sudo find / -type f -name openssl.pc
    - name: pkg-config openssl
      run: pkg-config --cflags --libs openssl
    - name: boot bsd
      uses: mario-campos/emulate@v1
      with:
        operating-system: ${{ matrix.os }}
    - name: hello world
      run: echo hello world
    - name: uname
      run: uname -a
    - name: df
      run: df -h
