name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [ openbsd-6.9, freebsd-12.2 ]
    steps:
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: |
        git clone https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        make hello
    - run: qemu-test/hello
