name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate:
    runs-on: macos-10.15
    steps:
    - uses: mario-campos/emulate@v1
      with:
        operating-system: netbsd-9.2
    - run: uname
    - run: |
        git clone --depth 1 https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        clang hello.c
        ./a.out
