name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install libstring-shellquote-perl
#     - uses: mario-campos/emulate@main
#       with:
#         operating-system: openbsd-6.9
