name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Bandwidth of Vagrant Cloud
      run: |
        echo testing vagrantcloud.com bandwidth
        curl -o vagrantcloud.box -L https://app.vagrantup.com/scotch/boxes/box/versions/3.5/providers/virtualbox.box
    - name: Test Bandwidth of GitHub
      run: |
        echo testing github.com bandwidth
        curl -o github.box -L https://github.com/mario-campos/qemu-test/releases/download/bandwidth-test/fbd109cd-1c36-424c-b463-3abc7726b342
    - name: Compare box
      run: cmp vagrantcloud.box github.box
