name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate-openbsd:
    runs-on: macos-10.15
    steps:
    - name: boot openbsd-7.0
      uses: mario-campos/emulate@emulate-images
      with:
        operating-system: openbsd-7.0
    - name: get disk size
      run: df -h
    - name: uname
      run: uname -a
