name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install libbsd0 libbsd-dev
    - run: ls -lR /usr/include
    - run: gcc --version
    - run: clang --version
    - run: gcc --help
    - run: clang --help
