name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-emulate-openbsd:
    runs-on: macos-10.15
    steps:
    - name: vagrant init
      run: vagrant init emulate/openbsd-7.0 --box-version 0.1.0
    - name: vagrant up
      run: vagrant up
    - name: vagrant ssh
      run: vagrant ssh -c 'uname -a'
