name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: general commands
      run: |
        export DISPLAY=':0.0'
        sudo xhost +
        brew install qemu libvirt dbus
        brew services start dbus
        sed -i .orig -e 's,#unix_sock_dir = "/usr/local/var/run/libvirt",unix_sock_dir = "/tmp",' /usr/local/etc/libvirt/libvirtd.conf
        /usr/local/opt/libvirt/sbin/libvirtd --verbose --config /usr/local/etc/libvirt/libvirtd.conf
        echo --- ls -l /tmp ---
        ls -al /tmp /usr/local/var/run/libvirt
        echo --- vagrant plugin ... ---
        vagrant plugin install vagrant-libvirt
        echo --- libvirtd --help ---
        libvirtd --help
        echo --- cat /usr/local/etc/libvirt/libvirtd.conf ---
        cat /usr/local/etc/libvirt/libvirtd.conf
        exit 1
    - uses: mario-campos/emulate@main
      with:
        operating-system: ${{ matrix.os }}
    - run: |
        git clone https://github.com/mario-campos/qemu-test.git
        cd qemu-test
        make hello
    - run: qemu-test/hello
