name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Check home directory
      run: |
        ls -l ~
        mkdir ~/.vagrant.d
    - name: Bootstrap VM
      run: sudo nice -n 20 vagrant up
    - name: Sanity check
      run: vagrant ssh -c 'uname -a'
