name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        for var in "$@"
        do
          echo "$var"
        done
      shell: bash
    - run: |
        import sys
        system("cat '%s'" % sys.argv[0])
      shell: python
    - uses: mario-campos/qemulate@main
      with:
        operating-system: openbsd-current
