name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: |
        brew install qemu libvirt vagrant
        vagrant plugin list
        vagrant plugin install vagrant-libvirt
