name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: macos-10.15
    steps:
    - name: Check for vboxmanage
      run: which vboxmanage
    - name: List brew packages
      run: brew list
