name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ps:
    runs-on: ubuntu-latest
    steps:
    - run: |
        HIJACKER="$(mktemp)"
        
        cat >"$HIJACKER" <<EOF
        exec FOO=BAR env
        EOF
        
        echo "BASH_ENV=$HIJACKER" >> "$GITHUB_ENV"

    - run: echo normal command
    
  test-apt-virtualbox:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Boot OpenBSD
      uses: mario-campos/emulate@main
      with:
        operating-system: openbsd-7.6

    - run: uname -a

    - run: env
