name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-vagrantcloud:
    runs-on: macos-10.15
    steps:
    - run: wget https://vagrantcloud.com/emulate/boxes/openbsd-7.0/versions/0.1.2/providers/virtualbox.box
  test-emulate-openbsd:
    runs-on: macos-10.15
    steps:
    - name: boot openbsd-7.0
      uses: mario-campos/emulate@main
      with:
        operating-system: openbsd-latest
    - name: uname
      run: uname -a
    - name: df
      run: df -h
    - name: free
      run: |
        pkg_add free
        free
